// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdYVxmoHTt4ehdzG9c5dpbRmHkVWWb18U',
    appId: '1:1079052461462:android:4ef8b015d1df095d5b69b7',
    messagingSenderId: '1079052461462',
    projectId: 'movies-app-db040',
    storageBucket: 'movies-app-db040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsjsewVLZkKO2qpXUwYwwwO56jXXUTRBg',
    appId: '1:1079052461462:ios:9f6c4ecd17111a335b69b7',
    messagingSenderId: '1079052461462',
    projectId: 'movies-app-db040',
    storageBucket: 'movies-app-db040.firebasestorage.app',
    androidClientId: '1079052461462-0a8nmd2jm2qov5pogno6ttal102pj1o3.apps.googleusercontent.com',
    iosClientId: '1079052461462-kvosr84ff6v05ma3u86tk10ferhs5bdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.movesFinalProject',
  );

}